name: 'Debug via NPS'
description: 'GitHub Actions NPC'
branding:
  icon: 'terminal'  
  color: 'green'
inputs:
  SSH_PASS:
    description: 'Password for SSH session'
    required: true
  SSH_IP:
    description: 'IP'
    required: true
  SSH_VKEY:
    description: 'VKEY'
    required: true  
    
runs:
  using: "composite"
  steps:
    - name: Change the SSH user password
      run: |
          echo runner:"${{ inputs.SSH_PASS }}" |sudo chpasswd runner
      shell: bash

    - name: Run ubuntu-start.sh
      run: source ubuntu-start.sh
      shell: bash

    - name: Install and setup NPC
      run: |
        echo "# Install NPC"
        wget https://github.com/ehang-io/nps/releases/download/v0.26.10/linux_amd64_client.tar.gz
        tar -zxvf linux_amd64_client.tar.gz
        chmod +x npc
        shell: bash
      
    - name: Start NPC
      run: |
        printf "# Starting NPC..."
        sleep 1
        ./npc -server="${{ inputs.SSH_IP }}" -vkey="${{ inputs.SSH_VKEY }}" -type=tcp &shell: bash

    - name: Run ubuntu-end.sh
      run: source ubuntu-end.sh
      shell: bash
