name: Ubuntu (nps)

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'ubuntu-18.04 | ubuntu-20.04'
        required: true
        default: 'ubuntu-20.04'
jobs:
  Instance:
    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Run Start Npc
      uses: helenpayne/NPS-Action2@master
      with:
        SSH_PASS: ${{ secrets.SSH_PASS }}
        SSH_IP: ${{ secrets.SSH_IP }}
        SSH_VKEY: ${{ secrets.SSH_VKEY }}
